// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;



public class ReportFilters2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","/Users/rosettamacuacua/wamly-auto/wamly-automation/front-end-auto/src/test/resources/drivers/mac/chrome/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void reportFilters2() {
    driver.get("https://ui.uatwamly.co.za/");
    driver.manage().window().setSize(new Dimension(1440, 900));
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("rosetta@wamly.io");
    driver.findElement(By.id("login-btn-2")).click();
    driver.findElement(By.id("password")).click();
    driver.findElement(By.cssSelector(".MuiIconButton-edgeEnd")).click();
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("Wamly@123");
    driver.findElement(By.id("login-btn")).click();
    driver.findElement(By.cssSelector("li:nth-child(1) .menu-label")).click();
    driver.findElement(By.cssSelector("li:nth-child(8) .menu-label")).click();
    driver.findElement(By.cssSelector(".ml-auto > span")).click();
    driver.findElement(By.id("searchTerm")).click();
    driver.findElement(By.id("searchTerm")).sendKeys("Motso");
    driver.findElement(By.id("filterUser")).click();
    assertThat(driver.findElement(By.cssSelector(".main-content")).getText(), is("Reports\\\\nCUSTOMISE TABLE\\\\nGENERATE REPORT\\\\nUSERS\\\\nPROJECTS\\\\nCANDIDATES\\\\nEMAIL LOGS\\\\nHide filter\\\\nUSER NAME\\\\nUSER LAST NAME\\\\nMOBILE NUMBER\\\\nEMAIL\\\\nSTATUS\\\\nDATE ADDED\\\\nMotso\\\\nMasondo\\\\n0718371303\\\\nkhmotso@wamly.io\\\\nACTIVE\\\\n2022-12-02\\\\n2022-12-02"));
    driver.findElement(By.id("resetUser")).click();
    driver.findElement(By.id("lastname")).click();
    driver.findElement(By.id("lastname")).sendKeys("Macuacua");
    driver.findElement(By.id("filterUser")).click();
    assertThat(driver.findElement(By.cssSelector(".main-content > .container-fluid")).getText(), is("Reports\\\\nCUSTOMISE TABLE\\\\nGENERATE REPORT\\\\nUSERS\\\\nPROJECTS\\\\nCANDIDATES\\\\nEMAIL LOGS\\\\nHide filter\\\\nUSER NAME\\\\nUSER LAST NAME\\\\nMOBILE NUMBER\\\\nEMAIL\\\\nSTATUS\\\\nDATE ADDED\\\\nRosetta\\\\nMacuacua\\\\n0735441158\\\\nrosettamacuacua@yahoo.com\\\\nINACTIVE\\\\n2021-08-10\\\\n2021-08-10\\\\nRosetta\\\\nMacuacua\\\\n0783451984\\\\nrosetta@wamly.io\\\\nACTIVE\\\\n2021-07-30\\\\n2021-07-30"));
    driver.findElement(By.id("resetUser")).click();
    driver.findElement(By.id("mobileNumber")).click();
    driver.findElement(By.id("mobileNumber")).sendKeys("0783451984");
    driver.findElement(By.id("filterUser")).click();
    driver.findElement(By.id("resetUser")).click();
    driver.findElement(By.id("userEmail")).click();
    driver.findElement(By.id("userEmail")).sendKeys("phillip@wamly.io");
    driver.findElement(By.id("filterUser")).click();
    assertThat(driver.findElement(By.cssSelector(".main-content")).getText(), is("Reports\\\\nCUSTOMISE TABLE\\\\nGENERATE REPORT\\\\nUSERS\\\\nPROJECTS\\\\nCANDIDATES\\\\nEMAIL LOGS\\\\nHide filter\\\\nUSER NAME\\\\nUSER LAST NAME\\\\nMOBILE NUMBER\\\\nEMAIL\\\\nSTATUS\\\\nDATE ADDED\\\\nKamogelo\\\\nBrown\\\\n0710226862\\\\nphillip@wamly.io\\\\nACTIVE\\\\n2022-11-01\\\\n2022-12-15"));
    driver.findElement(By.id("resetUser")).click();
    driver.findElement(By.cssSelector(".ml-auto > span")).click();
  }
}
